services:
  pgdatabase:
    image: postgres:18
    container_name: pgdatabase
    network_mode: "host"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql
    stdin_open: true
    tty: true

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    network_mode: "host"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 8085
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    stdin_open: true
    tty: true

  taxi_ingest:
    build: .
    image: taxi_ingest:v001
    container_name: taxi_ingest
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - .:/code
      - /code/.venv
    command:
      - --pg-user=root
      - --pg-pass=root
      - --pg-host=localhost
      - --pg-port=5432
      - --pg-db=ny_taxi
      - --target-table=yellow_taxi_trips
      - --year=2021
      - --month=1
    depends_on:
      - pgdatabase

volumes:
  ny_taxi_postgres_data:
  pgadmin_data: