#!/usr/bin/env python
# coding: utf-8

import os
import pandas as pd
from tqdm.auto import tqdm
from sqlalchemy import create_engine
import click
from openai import OpenAI
import anthropic
import matplotlib.pyplot as plt
import seaborn as sns

# Initialize clients securely from environment variables
# Initialize clients securely and strip ALL quotes/spaces passed by Docker
oai_env = os.getenv("OPENAI_API_KEY")
openai_api_key = oai_env.strip().strip("\"'") if oai_env else None
openai_client = OpenAI(api_key=openai_api_key) if openai_api_key else None

ant_env = os.getenv("ANTHROPIC_API_KEY")
anthropic_api_key = ant_env.strip().strip("\"'") if ant_env else None
anthropic_client = anthropic.Anthropic(api_key=anthropic_api_key) if anthropic_api_key else None

print(f"\n[SYSTEM] OpenAI Key Loaded: {'✅ YES' if openai_client else '❌ NO'}")
print(f"[SYSTEM] Anthropic Key Loaded: {'✅ YES' if anthropic_client else '❌ NO'}\n")

def detect_anomalies(df_sample, suspicious_sample):
    print("\n--- Generating Visualizations ---")
    os.makedirs("images", exist_ok=True)
    
    # Draw scatter plot: Trip Distance vs. Fare Amount
    plt.figure(figsize=(10, 6))
    sns.scatterplot(data=df_sample, x='trip_distance', y='fare_amount', color='blue', alpha=0.3, label='Normal Sample')
    sns.scatterplot(data=suspicious_sample, x='trip_distance', y='fare_amount', color='red', s=100, label='Flagged Anomalies')
    
    plt.title('NYC Taxi: Trip Distance vs. Fare Amount')
    plt.xlabel('Trip Distance (miles)')
    plt.ylabel('Fare Amount ($)')
    plt.grid(True, linestyle='--', alpha=0.7)
    
    chart_path = 'images/anomaly_scatter.png'
    plt.savefig(chart_path)
    plt.close()
    print(f"Visualization saved to {chart_path}")

    # Prepare prompt
    prompt = f"Analyze this flagged NYC taxi data sample. Explain why these specific rows are physically impossible or highly anomalous based on standard taxi operations:\n{suspicious_sample.to_string()}"
    
    oai_text = "OpenAI API key missing or request failed."
    ant_text = "Anthropic API key missing or request failed."

    print("\n[Requesting OpenAI Analysis]")
    if openai_client:
        try:
            oai_res = openai_client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}]
            )
            oai_text = oai_res.choices[0].message.content
        except Exception as e:
            print(f"OpenAI Error: {e}")

    print("[Requesting Anthropic Analysis]")
    if anthropic_client:
        try:
            ant_res = anthropic_client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=500,
                messages=[{"role": "user", "content": prompt}]
            )
            ant_text = ant_res.content[0].text
        except Exception as e:
            print(f"Anthropic Error: {e}")

    # Write Markdown Report
    print("\n--- Writing AI_INSIGHTS.md ---")
    with open("AI_INSIGHTS.md", "w", encoding="utf-8") as f:
        f.write("# 🚕 NYC Taxi Data: Automated AI Anomaly Report\n\n")
        f.write("This report is generated by the ingestion pipeline to flag data quality issues before warehouse loading.\n\n")
        
        f.write("## 📊 Anomaly Visualization\n")
        f.write("Red dots represent flagged records matching strict error criteria (e.g., negative fares, zero passengers, impossible distance-to-fare ratios).\n\n")
        f.write(f"![Distance vs Fare]({chart_path})\n\n")
        
        f.write("## 🤖 OpenAI Quality Check\n")
        f.write(oai_text + "\n\n")
        
        f.write("## 🧠 Anthropic Quality Check\n")
        f.write(ant_text + "\n\n")
        
        f.write("## 📋 Raw Suspicious Data\n")
        f.write(suspicious_sample.to_markdown() + "\n")
        
    print("Report generated successfully! Check AI_INSIGHTS.md")

dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

@click.command()
@click.option("--pg-user", default="root", show_default=True)
@click.option("--pg-pass", default="root", show_default=True)
@click.option("--pg-host", default="localhost", show_default=True)
@click.option("--pg-db", default="ny_taxi", show_default=True)
@click.option("--pg-port", type=int, default=5432, show_default=True)
@click.option("--target-table", default="yellow_taxi_trips", show_default=True)
@click.option("--year", type=int, default=2021, show_default=True)
@click.option("--month", type=click.IntRange(1, 12), default=1, show_default=True)
@click.option("--chunk-size", type=click.IntRange(min=1), default=100000, show_default=True)
def run(pg_user, pg_pass, pg_host, pg_db, pg_port, target_table, year, month, chunk_size):
    
    prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'
    url = f'{prefix}/yellow_tripdata_{year}-{month:02d}.csv.gz'
    
    engine = create_engine(
        f'postgresql+psycopg://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'
    )

    # --- AI DATA QUALITY CHECK ---
    print(f"Reading sample for anomaly detection from {url}...")
    df_sample = pd.read_csv(url, dtype=dtype, parse_dates=parse_dates, nrows=10000)
    
    # Advanced Pandas Logic: Hunt for actual errors
    anomalies = df_sample[
        (df_sample['fare_amount'] <= 0) | 
        (df_sample['passenger_count'] == 0) | 
        ((df_sample['trip_distance'] == 0) & (df_sample['fare_amount'] > 5.00)) |
        (df_sample['fare_amount'] > 100)
    ]
    
    # Take the top 15 most extreme anomalies to save API tokens
    suspicious_sample = anomalies.sort_values(by='fare_amount', ascending=False).head(15)
    
    print("\n--- Running AI Data Quality Check ---")
    if not suspicious_sample.empty:
        detect_anomalies(df_sample, suspicious_sample)
    else:
        print("No severe anomalies found in the first 10,000 rows. Skipping AI check.")
    print("-----------------------------------\n")

    # --- EXISTING INGESTION LOGIC ---
    print("Starting database ingestion...")
    df_iter = pd.read_csv(
        url,
        dtype=dtype,
        parse_dates=parse_dates,
        chunksize=chunk_size,
    )

    first = True
    for df_chunk in tqdm(df_iter, desc="Ingesting"):
        if first:
            df_chunk.head(0).to_sql(name=target_table, con=engine, if_exists='replace')
            first = False
        df_chunk.to_sql(name=target_table, con=engine, if_exists='append')

if __name__ == '__main__':
    run()